services:
  db:
    image: postgres:16
    container_name: frisbee_pg
    environment:
      POSTGRES_DB: frisbee
      POSTGRES_USER: frisbee
      POSTGRES_PASSWORD: frisbee
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
